import Link from 'next/link';
import {
  FileText,
  ShieldCheck,
  ArrowLeft,
  Sparkles,
  CheckCircle,
  Globe,
  Lock,
  Scale,
  AlertTriangle,
  HelpCircle,
} from 'lucide-react';

export const metadata = {
  title: 'Terms & Conditions | Content Sync',
  description: 'Terms of Service and Conditions of Use for Content Sync Multi-Workspace Social Automation Platform.',
};

export default function TermsPage() {
  const lastUpdated = 'August 2, 2026';

  const sections = [
    {
      id: 'acceptance',
      title: '1. Acceptance of Terms',
      icon: CheckCircle,
      content: `By accessing, registering for, or using Content Sync ("Service", "Platform", "We", "Us", or "Our"), you ("User", "Subscriber", "You") agree to be bound by these Terms & Conditions ("Terms"). If you are accepting these Terms on behalf of a company, organization, or other legal entity, you represent and warrant that you have full legal authority to bind such entity. If you do not agree to all of these Terms, you must immediately cease using the Service.`,
    },
    {
      id: 'accounts',
      title: '2. Account Registration & Workspace Access',
      icon: Lock,
      content: `To utilize Content Sync, you must register for an account and maintain accurate, up-to-date credential information. You are solely responsible for maintaining the confidentiality of your account credentials, API tokens, and connected social media authentication keys.

- You must be at least 18 years of age (or the legal age of majority in your jurisdiction) to create an account.
- Each workspace created within Content Sync must correspond to a domain or business entity you own or are legally authorized to represent.
- You are responsible for all activities, automated jobs, content scheduling, and third-party API triggers occurring under your account.`,
    },
    {
      id: 'scraping-rss',
      title: '3. Web Scraping & RSS Synchronization Compliance',
      icon: Globe,
      content: `Content Sync provides tools to scrape public blog posts, RSS feeds, and web URLs to extract text for automated content generation. By using these features:

- You warrant that you own or have explicit rights, licenses, or authorization to fetch, parse, and re-purpose content from any target URL or RSS feed added to Content Sync.
- You agree NOT to use Content Sync to scrape or harvest content from websites that explicitly prohibit automated data collection in their robots.txt file or Terms of Service.
- You accept full legal liability for any copyright infringement or unauthorized content parsing resulting from URLs inputted into the platform.`,
    },
    {
      id: 'ai-generation',
      title: '4. AI Content Generation & Intellectual Property Rights',
      icon: Sparkles,
      content: `Content Sync utilizes large language models (LLMs) and generative AI services (including OpenAI, Anthropic, and proprietary algorithms) to assist in drafting social media posts, carousel slides, and video scripts.

- Ownership of Output: Subject to your compliance with these Terms, you retain ownership of all final text and media generated by you through Content Sync.
- AI Disclaimer: Generative AI outputs may occasionally contain factual errors, hallucinations, or inappropriate phrasing. You are solely responsible for reviewing, editing, and verifying all AI-generated content before publication.
- License to Service Provider: You grant Content Sync a non-exclusive, worldwide, royalty-free license to store, process, and transmit your input data solely for providing, maintaining, and improving the Service.`,
    },
    {
      id: 'social-apis',
      title: '5. Social Media Platform Integrations & API Terms',
      icon: ShieldCheck,
      content: `Content Sync integrates with third-party social media networks including, but not limited to, Meta (Facebook Pages, Instagram), X (formerly Twitter), LinkedIn, Threads, Pinterest, Telegram, and Discord.

- Compliance with Platform Policies: Your use of Content Sync to publish content to third-party social channels must comply with each platform's respective Terms of Service, Community Guidelines, and Developer API Policies.
- Account Sanctions: Content Sync is not responsible for any rate limiting, shadowbanning, account suspension, or deletion imposed by third-party social platforms due to your posting frequencies or content strategy.
- OAuth Credentials: Content Sync securely encrypts third-party access tokens. Revoking OAuth access on a third-party platform will disable automated posting features within Content Sync.`,
    },
    {
      id: 'billing',
      title: '6. Subscriptions, Payments & Renewal Terms',
      icon: Scale,
      content: `Certain features of Content Sync are billed on a subscription basis (Monthly or Annually).

- Billing Cycles: Subscriptions automatically renew at the end of each billing cycle unless cancelled prior to the renewal date.
- Refunds: Subscriptions are non-refundable except where required by applicable consumer protection laws. Pro-rated refunds are not issued for mid-cycle cancellations.
- Workspace Limits: Usage limits (e.g., number of connected websites, monthly AI word generation credits, social posting quotas) are determined by your selected plan. Exceeding limits may require plan upgrades or overage charges.`,
    },
    {
      id: 'prohibited',
      title: '7. Acceptable Use & Prohibited Conduct',
      icon: AlertTriangle,
      content: `You agree NOT to use Content Sync to:

- Distribute spam, unauthorized commercial communications, malware, or phishing campaigns.
- Generate or post defamatory, illegal, harassing, hate speech, or infringing content.
- Reverse engineer, decompile, or extract the source code of Content Sync.
- Circumvent rate limits, access controls, or security mechanisms of the Service.
- Share account credentials or re-sell access to unauthorized third parties.`,
    },
    {
      id: 'liability',
      title: '8. Limitation of Liability & Warranty Disclaimer',
      icon: Scale,
      content: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:

- Content Sync IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED.
- WE DO NOT GUARANTEE THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE.
- IN NO EVENT SHALL Content Sync, ITS DIRECTORS, EMPLOYEES, OR PARTNERS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE.
- OUR AGGREGATE LIABILITY SHALL NOT EXCEED THE TOTAL AMOUNT PAID BY YOU TO Content Sync IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.`,
    },
    {
      id: 'termination',
      title: '9. Termination & Account Suspension',
      icon: AlertTriangle,
      content: `We reserve the right to suspend or terminate your account immediately, without prior notice or liability, for any breach of these Terms, non-payment of fees, or court order. Upon termination, your right to use the Service will cease immediately, and stored data may be permanently deleted in accordance with our retention policy.`,
    },
    {
      id: 'contact',
      title: '10. Governing Law & Contact Information',
      icon: HelpCircle,
      content: `These Terms shall be governed and construed in accordance with applicable governing laws, without regard to conflict of law principles.

If you have any questions or legal inquiries regarding these Terms & Conditions, please contact us:

- Email: legal@contentsync.ai
- Support Center: https://contentsync.ai/support
- Official Address: Content Sync Corp., Legal & Compliance Dept.`,
    },
  ];

  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-100 font-sans selection:bg-blue-500 selection:text-white">
      {/* Header Banner */}
      <header className="border-b border-zinc-800/80 bg-zinc-900/50 backdrop-blur-md sticky top-0 z-30">
        <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Link href="/" className="flex items-center gap-3 hover:opacity-90 transition">
              <div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-blue-600 via-indigo-500 to-purple-500 flex items-center justify-center font-bold text-white shadow-lg shadow-blue-500/20">
                CS
              </div>
              <span className="font-extrabold text-lg tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-blue-400 via-indigo-300 to-white">
                Content Sync
              </span>
            </Link>
          </div>

          <div className="flex items-center gap-4">
            <Link
              href="/"
              className="px-4 py-2 rounded-xl bg-zinc-900 border border-zinc-800 hover:bg-zinc-800 text-zinc-300 text-xs font-semibold flex items-center gap-2 transition"
            >
              <ArrowLeft className="w-4 h-4" />
              <span>Back to Home</span>
            </Link>
            <Link
              href="/dashboard"
              className="px-4 py-2 rounded-xl bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold shadow-md shadow-blue-600/30 transition"
            >
              Go to Dashboard
            </Link>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <div className="relative border-b border-zinc-800/60 bg-gradient-to-b from-zinc-900/80 to-zinc-950 py-16 px-6">
        <div className="max-w-4xl mx-auto text-center space-y-4">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full text-xs font-bold bg-blue-500/10 text-blue-400 border border-blue-500/20">
            <FileText className="w-4 h-4" />
            <span>Legal Documentation</span>
          </div>
          <h1 className="text-4xl sm:text-5xl font-extrabold tracking-tight text-white">
            Terms & Conditions
          </h1>
          <p className="text-zinc-400 text-sm sm:text-base max-w-2xl mx-auto">
            Please read these terms carefully before using Content Sync. By using our multi-workspace social automation service, you agree to these legal conditions.
          </p>
          <div className="pt-2 text-xs text-zinc-500 font-mono">
            Last Updated: {lastUpdated} &bull; Version 2.4.0
          </div>
        </div>
      </div>

      {/* Main Content Area */}
      <main className="max-w-7xl mx-auto px-6 py-12 grid grid-cols-1 lg:grid-cols-4 gap-10">
        {/* Table of Contents Sidebar */}
        <aside className="lg:col-span-1 space-y-4 hidden lg:block sticky top-28 h-fit">
          <div className="p-5 rounded-2xl bg-zinc-900/60 border border-zinc-800 space-y-3">
            <h3 className="text-xs font-bold uppercase tracking-wider text-zinc-400">
              On This Page
            </h3>
            <nav className="space-y-1 text-xs">
              {sections.map((section) => (
                <a
                  key={section.id}
                  href={`#${section.id}`}
                  className="block py-1.5 px-2.5 rounded-lg text-zinc-400 hover:text-white hover:bg-zinc-800/60 transition truncate"
                >
                  {section.title}
                </a>
              ))}
            </nav>
          </div>

          <div className="p-5 rounded-2xl bg-blue-950/30 border border-blue-900/40 text-xs space-y-2">
            <h4 className="font-bold text-blue-400 flex items-center gap-2">
              <ShieldCheck className="w-4 h-4" />
              Need Legal Clarification?
            </h4>
            <p className="text-zinc-400 leading-relaxed">
              If you have specific compliance requirements or enterprise legal questions, reach out to our legal team.
            </p>
            <a
              href="mailto:legal@contentpilot.ai"
              className="text-blue-400 font-semibold underline block hover:text-blue-300"
            >
              legal@contentpilot.ai
            </a>
          </div>
        </aside>

        {/* Legal Clauses List */}
        <section className="lg:col-span-3 space-y-8">
          {sections.map((section) => {
            const Icon = section.icon;
            return (
              <div
                key={section.id}
                id={section.id}
                className="p-8 rounded-3xl glass border border-white/[0.06] hover:border-white/[0.10] space-y-4 transition card-hover"
              >
                <div className="flex items-center gap-3">
                  <div className="p-2.5 rounded-2xl bg-gradient-to-tr from-blue-600 to-indigo-600 text-white shadow-md shadow-blue-500/20">
                    <Icon className="w-5 h-5" />
                  </div>
                  <h2 className="text-xl font-bold text-white tracking-tight">
                    {section.title}
                  </h2>
                </div>
                <div className="text-zinc-300 text-sm leading-relaxed whitespace-pre-line font-sans">
                  {section.content}
                </div>
              </div>
            );
          })}

          {/* Bottom Footer Notice */}
          <div className="p-6 rounded-2xl glass border border-white/[0.06] text-center text-xs text-zinc-400 space-y-2">
            <p>&copy; {new Date().getFullYear()} Content Sync Inc. All rights reserved.</p>
            <div className="flex items-center justify-center gap-4 text-zinc-500 pt-1">
              <Link href="/privacy" className="hover:text-zinc-300 transition">
                Privacy Policy
              </Link>
              <span>&bull;</span>
              <Link href="/terms" className="hover:text-zinc-300 transition">
                Terms of Service
              </Link>
              <span>&bull;</span>
              <Link href="/data-deletion" className="hover:text-zinc-300 transition">
                Data Deletion
              </Link>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
